jobs:
  coverage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Generate Coverage Data
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: cobertura
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
        distributions-cache-enabled: true
    - continue-on-error: true
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
        files: build/reports/cobertura/coverage.xml
name: Code coverage
on:
  repository_dispatch:
    types: trigger-ga___cobertura.yaml
