jobs:
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Run Gradle Tests
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: check
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
        distributions-cache-enabled: true
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yaml
